# **NUMPY**
NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. Here are some key features and concepts of NumPy:

In [1]:
import numpy as np

The arange() function is used to create an array with regularly spaced values within a specified range.

In [2]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

The linspace() function is used to create an array with a specified number of evenly spaced values within a specified range. Unlike arange(), which generates values based on a step size, linspace() generates values based on the number of elements desired in the output array.

In [4]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

 The logspace() function is used to create an array with a specified number of logarithmically spaced values within a specified range. It is similar to the linspace() function, but instead of generating evenly spaced values, logspace() generates values that are evenly spaced on a logarithmic scale.

In [5]:
np.logspace(2, 4, 8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

The random module provides various functions for generating random numbers and random arrays. These functions allow you to generate random values from different probability distributions, as well as random arrays of specified shapes and sizes. Here are a few commonly used functions from the random module:

rand(): This function generates random numbers from a uniform distribution over the range [0, 1]. It returns an array or a single random value.

randint(): This function generates random integers from a specified range. The range is inclusive of the lower bound and exclusive of the upper bound.

random(): This function generates random numbers from a continuous uniform distribution over the range [0, 1]. It returns an array or a single random value.

randn(): This function generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

choice(): This function randomly selects elements from a given array with replacement.

In [7]:
np.random.randint(1, 10, 5)

array([3, 9, 6, 9, 1])

In [8]:
column = 6
rows = 8
patterns = [[np.random.randint(1, 10) for i in range (column)]  for j in range (rows)]
for rows in patterns:
  print(rows)

[5, 5, 7, 3, 1, 1]
[9, 1, 6, 9, 4, 6]
[6, 3, 1, 8, 5, 4]
[4, 9, 4, 5, 9, 8]
[4, 4, 3, 6, 5, 8]
[5, 3, 5, 7, 3, 7]
[4, 4, 9, 5, 6, 7]
[6, 3, 3, 4, 9, 5]


In [9]:
# in simple way
d = np.random.randint(1, 10, size=(6, 6))

In [10]:
d

array([[5, 2, 4, 9, 8, 6],
       [4, 6, 9, 9, 7, 6],
       [4, 1, 5, 5, 9, 1],
       [5, 2, 5, 3, 1, 3],
       [8, 7, 7, 8, 2, 9],
       [8, 8, 6, 5, 8, 9]])

**INDEXING**:

Indexing in NumPy allows you to access specific elements or subsets of elements in an array. You can use indexing to retrieve individual elements, rows, columns, or subarrays based on their positions or conditions.

In [11]:
d[:,:]

array([[5, 2, 4, 9, 8, 6],
       [4, 6, 9, 9, 7, 6],
       [4, 1, 5, 5, 9, 1],
       [5, 2, 5, 3, 1, 3],
       [8, 7, 7, 8, 2, 9],
       [8, 8, 6, 5, 8, 9]])

In [12]:
d[:,2:5]

array([[4, 9, 8],
       [9, 9, 7],
       [5, 5, 9],
       [5, 3, 1],
       [7, 8, 2],
       [6, 5, 8]])

In [13]:
d[:,3]

array([9, 9, 5, 3, 8, 5])

In [14]:
d[1:4,2:6]

array([[9, 9, 7, 6],
       [5, 5, 9, 1],
       [5, 3, 1, 3]])

In [15]:
a = np.ones((4,4))

In [16]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
b = np.zeros((4,4))

In [18]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Concatenation**:
The concatenate() function is used to join two or more arrays along a specified axis. It allows you to combine arrays either vertically (along rows) or horizontally (along columns). The arrays being concatenated must have the same shape in all dimensions, except the one along which they are being concatenated.

In [19]:
np.concatenate([a, b])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# if axis = 1
np.concatenate([a, b], axis = 1)

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [21]:
# if axis = 0
np.concatenate([a, b], axis = 0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Split**:
The split() function is used to split an array into multiple subarrays along a specified axis. It divides the array into equal-sized or nearly equal-sized parts and returns a list of subarrays.

In [22]:
d

array([[5, 2, 4, 9, 8, 6],
       [4, 6, 9, 9, 7, 6],
       [4, 1, 5, 5, 9, 1],
       [5, 2, 5, 3, 1, 3],
       [8, 7, 7, 8, 2, 9],
       [8, 8, 6, 5, 8, 9]])

In [23]:
np.split(d, 2)

[array([[5, 2, 4, 9, 8, 6],
        [4, 6, 9, 9, 7, 6],
        [4, 1, 5, 5, 9, 1]]),
 array([[5, 2, 5, 3, 1, 3],
        [8, 7, 7, 8, 2, 9],
        [8, 8, 6, 5, 8, 9]])]

vsplit(): This function splits an array vertically into multiple subarrays by specifying the number of equally-sized parts or the indices at which to split the array.

In [24]:
np.vsplit(d, 3)

[array([[5, 2, 4, 9, 8, 6],
        [4, 6, 9, 9, 7, 6]]),
 array([[4, 1, 5, 5, 9, 1],
        [5, 2, 5, 3, 1, 3]]),
 array([[8, 7, 7, 8, 2, 9],
        [8, 8, 6, 5, 8, 9]])]

hsplit(): This function splits an array horizontally into multiple subarrays by specifying the number of equally-sized parts or the indices at which to split the array.

In [25]:
np.hsplit(d, 2)

[array([[5, 2, 4],
        [4, 6, 9],
        [4, 1, 5],
        [5, 2, 5],
        [8, 7, 7],
        [8, 8, 6]]),
 array([[9, 8, 6],
        [9, 7, 6],
        [5, 9, 1],
        [3, 1, 3],
        [8, 2, 9],
        [5, 8, 9]])]

shape: The shape function returns a tuple of integers that represents the dimensions of the array. Each integer in the tuple corresponds to the size of the array along that particular dimension.

size: The size function returns the total number of elements in the array. It returns an integer representing the size of the array.

ndim: The ndim function returns the number of dimensions of the array. It returns an integer representing the number of axes or dimensions in the array.

In [26]:
d

array([[5, 2, 4, 9, 8, 6],
       [4, 6, 9, 9, 7, 6],
       [4, 1, 5, 5, 9, 1],
       [5, 2, 5, 3, 1, 3],
       [8, 7, 7, 8, 2, 9],
       [8, 8, 6, 5, 8, 9]])

In [27]:
d.shape

(6, 6)

In [28]:
d.size

36

In [29]:
d.ndim

2

Reshaping: The reshape() function is used to change the shape of an array without altering its data. Reshaping allows you to rearrange the elements of an array into a different shape, as long as the total number of elements remains the same.

In [30]:
d

array([[5, 2, 4, 9, 8, 6],
       [4, 6, 9, 9, 7, 6],
       [4, 1, 5, 5, 9, 1],
       [5, 2, 5, 3, 1, 3],
       [8, 7, 7, 8, 2, 9],
       [8, 8, 6, 5, 8, 9]])

In [31]:
d.reshape(9, 4)

array([[5, 2, 4, 9],
       [8, 6, 4, 6],
       [9, 9, 7, 6],
       [4, 1, 5, 5],
       [9, 1, 5, 2],
       [5, 3, 1, 3],
       [8, 7, 7, 8],
       [2, 9, 8, 8],
       [6, 5, 8, 9]])

**Dimension addition**

Newaxis is a special indexing object that is used to increase the dimensions of an array by one. It is used to insert a new axis into an existing array at a specified position. The newaxis object is typically used during array manipulations or broadcasting operations to align the shapes of arrays.

In [32]:
s = np.array([1,2,3,4,5])

In [33]:
s

array([1, 2, 3, 4, 5])

In [34]:
x = s[:, np.newaxis]
x

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [35]:
x.shape

(5, 1)

In [36]:
y = s[:, np.newaxis, np.newaxis]
y

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [37]:
y.shape

(5, 1, 1)

**Mathematical Funactions**

NumPy has huge list of mathematical functions to make implementation of Machine Learning algorithms easily.

Few of them are:



*   Max                             
*   Min
*   Mean
*   Std
*   Cov
*   Cumprod
*   All
*   Any
*   Sum
*   Dot
*   Multiply
*   Sqrt



In [38]:
d

array([[5, 2, 4, 9, 8, 6],
       [4, 6, 9, 9, 7, 6],
       [4, 1, 5, 5, 9, 1],
       [5, 2, 5, 3, 1, 3],
       [8, 7, 7, 8, 2, 9],
       [8, 8, 6, 5, 8, 9]])

In [39]:
np.sum(d, axis = 1)

array([34, 41, 25, 19, 41, 44])

In [40]:
np.sqrt(4)

2.0

In [41]:
np.max(d)

9

In [42]:
np.min(d)

1

**Broadcasting**

Broadcasting is a powerful feature in NumPy that allows for implicit element-wise operations between arrays of different shapes and sizes. It eliminates the need for explicit loops or manual alignment of array shapes, making code more concise and efficient.

In NumPy, broadcasting works by automatically extending or "broadcasting" smaller arrays to match the shape of larger arrays. The broadcasting rules determine how arrays with different shapes are aligned and how the element-wise operations are performed.

In [43]:
a = np.array([5, 3, 2])
a

array([5, 3, 2])

In [44]:
b = np.array([4, 7, 8])
b

array([4, 7, 8])

In [45]:
#Broadcasting

c = a + b
c

array([ 9, 10, 10])

Different size and shape can cause error in broadcasting

In [51]:
i = np.array([[2,3,4], [5,7,8]])
j = np.array([[2,3,4], [9,7,8], [2,7,4]])

In [52]:
k = i + j

ValueError: ignored

Therefore dimension should be increased of array.

In [53]:
i.shape

(2, 3)

In [54]:
j.shape

(3, 3)

In [55]:
k = i.reshape(1,2,3) + j.reshape(3,1,3)
k

array([[[ 4,  6,  8],
        [ 7, 10, 12]],

       [[11, 10, 12],
        [14, 14, 16]],

       [[ 4, 10,  8],
        [ 7, 14, 12]]])